spring.application.name=appliweb

format.date=dd/MM/yyyy

spring.profile.active=${SPRING_PROFILE_ACTIVE:local}

spring.datasource.url=jdbc:mysql://localhost:3306/recensement
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update